### ISSUE TITLE
Recompile Error Message

### ISSUE THREAD

**Issue by andrenventer** [juxt/edge#10]
Compiling ClojureScript...
? edge.js
Writing target dir(s)...
java.net.BindException
: Address already in use

...                    

clojure.tools.nrepl.server/start-server/invokeStatic

server.clj: 
 143

clojure.tools.nrepl.server/start-server  
        server.clj
: 
 121

...  

clojure.core/apply/invokeStatic  
          core.clj
:  
646

clojure.core/apply  

core.clj: 
 641

```
      boot.repl-server/start-server/invokeStatic
```

repl_server.clj: 
  83

```
                   boot.repl-server/start-server     repl_server.clj:   66
                          boot.repl/launch-nrepl            repl.clj:   51
                          boot.core/launch-nrepl            core.clj: 1228
                                             ...                          
                 clojure.core/apply/invokeStatic            core.clj:  646
                              clojure.core/apply            core.clj:  641
                     boot.task.built-in/fn/fn/fn        built_in.clj:  392
                                             ...                          
                 clojure.core/deref/invokeStatic            core.clj: 2228
                              clojure.core/deref            core.clj: 2214
                  boot.task.built-in/fn/fn/fn/fn        built_in.clj:  395
                  boot.task.built-in/fn/fn/fn/fn  
  built_in.clj:  
```

303
                   adzerk.boot-cljs/eval294/fn/fn/fn

boot_cljs.clj: 
 201

```
               adzerk.boot-cljs/eval242/fn/fn/fn
```

boot_cljs.clj: 
 135

```
          adzerk.boot-cljs-repl/eval396/fn/fn/fn
```

  boot_cljs_repl.clj
: 
 164

```
                  boot.task.built-in/fn/fn/fn/fn

  built_in.clj: 
```

396

boot.task.built-in/fn/fn/fn/fn  
      built_in.clj
: 
 394

```
          adzerk.boot-reload/eval521/fn/fn/fn/fn
```

   boot_reload.clj: 
 140

adzerk.boot-reload/eval521/fn/fn/fn  
   boot_reload.clj
: 
 139

deraen.boot-sass/eval613/fn/fn/fn  

boot_sass.clj: 

46

```
                  boot.task.built-in/fn/fn/fn/fn
```

built_in.clj: 
 167

```
            boot.task.built-in/fn/fn/fn/fn/fn/fn

  built_in.clj
```

: 
 348

```
               boot.task.built-in/fn/fn/fn/fn/fn

  built_in.clj
```

: 
 348

boot.task.built-in/fn/fn/fn/fn  

built_in.clj: 
 345

boot.core/run-tasks  
          core.clj
: 
 938

```
                               boot.core/boot/fn
```

core.clj
: 
 948

clojure.core/binding-conveyor-fn/fn  
          core.clj: 
1938
                                                 ...  

Elapsed time: 0.546 sec

**Comment by malcolmsparks** [comment]
Closing now we've migrated to deps.edn
