### ISSUE TITLE
Repl start Error Message

### ISSUE THREAD

**Issue by andrenventer** [juxt/edge#11]
Starting REPL with boot in /Users/nomad/Projects/edge
Starting reload server on ws://localhost:49485
Writing adzerk/boot_reload/init28534.cljs to connect to ws://localhost:49485...
Writing boot_cljs_repl.cljs...
11:05:34.511 [clojure-agent-send-off-pool-0] INFO  edge.web-server - Started web-server on port 3000

Starting file watcher (CTRL-C to quit)...

Compiling {sass}... 8 changed files.
Adding :require adzerk.boot-reload.init28534 to edge.cljs.edn...
nREPL server started on port 5600 on host 127.0.0.1 - nrepl://127.0.0.1:5600
Adding :require adzerk.boot-cljs-repl to edge.cljs.edn...
Compiling ClojureScript...
? edge.js
user=>
Refreshing code...
:reloading (edge.phonebook-app edge.selmer edge.phonebook.schema edge.phonebook.db edge.phonebook edge.sources edge.hello edge.web-server edge.system user)
Refresh complete
Writing target dir(s)...
java.net.BindException
: 
Address already in use

...                    

clojure.tools.nrepl.server/start-server/invokeStatic

```
    server.clj:  143
```

clojure.tools.nrepl.server/start-server

server.clj: 
 121
                                                 ...

clojure.core/apply/invokeStatic

```
      core.clj
```

: 

646

```
                              clojure.core/apply

      core.clj
```

: 

641

```
      boot.repl-server/start-server/invokeStatic
```

repl_server.clj: 

83

boot.repl-server/start-server  

repl_server.clj: 

66
                              boot.repl/launch-nrepl  
repl.clj: 

51

boot.core/launch-nrepl            core.clj
: 
1228

...

clojure.core/apply/invokeStatic

core.clj
: 
 646

clojure.core/apply

core.clj
: 

641

boot.task.built-in/fn/fn/fn
        built_in.clj
:  392
                                                 ...

```
                 clojure.core/deref/invokeStatic
```

core.clj
: 
2228

```
                              clojure.core/deref            core.clj: 2214

                  boot.task.built-in/fn/fn/fn/fn  
```

built_in.clj
:  
395

boot.task.built-in/fn/fn/fn/fn

```
  built_in.clj
```

: 

303
                   adzerk.boot-cljs/eval294/fn/fn/fn  
     boot_cljs.clj
: 
 201

```
               adzerk.boot-cljs/eval242/fn/fn/fn       boot_cljs.clj:  135
          adzerk.boot-cljs-repl/eval396/fn/fn/fn  boot_cljs_repl.clj
```

:  164
                      boot.task.built-in/fn/fn/fn/fn        built_in.clj:  396
                      boot.task.built-in/fn/fn/fn/fn        built_in.clj: 

394
              adzerk.boot-reload/eval521/fn/fn/fn/fn
     boot_reload.clj:  
140

adzerk.boot-reload/eval521/fn/fn/fn  

boot_reload.clj
: 
 139

deraen.boot-sass/eval613/fn/fn/fn

```
 boot_sass.clj
```

: 

46

boot.task.built-in/fn/fn/fn/fn

built_in.clj: 

167

boot.task.built-in/fn/fn/fn/fn/fn/fn  

built_in.clj: 

348

```
               boot.task.built-in/fn/fn/fn/fn/fn        built_in.clj
```

: 
 348

boot.task.built-in/fn/fn/fn/fn  

built_in.clj: 

345

boot.core/run-tasks  

core.clj
: 
 938

boot.core/boot/fn  

core.clj: 

948

```
             clojure.core/binding-conveyor-fn/fn
```

core.clj: 
1938

...

Elapsed time: 39.235 sec

**Comment by SevereOverfl0w** [comment]
Can you explain the steps to reproduce this error? How did you trigger the refresh?

**Comment by andrenventer** [comment]
Atom proto-repl triggered the refresh

https://atom.io/
https://atom.io/packages/proto-repl

**Comment by malcolmsparks** [comment]
Closing now we've migrated to deps.edn
