### ISSUE TITLE
:edge.yada.ig/redirect :opts parameter

### ISSUE THREAD

**Issue by pwhittin** [juxt/edge#113]
In the file **built-in-libraries.adoc** the **:edge.yada.ig/redirect** bullet documents a second parameter referred to as **:opts**.  The example uses a second parameter referred to as **:route-params**.  This is confusing at best, and incorrect at worst.

**Comment by SevereOverfl0w** [comment]
You're right, the `:route-params` key is missing an `:opts` around it.

**Comment by SevereOverfl0w** [comment]
I've deployed the updated docs, thanks for the report!
