### ISSUE TITLE
No method in multimethod 'init-key'   Error

### ISSUE THREAD

**Issue by tbrooke** [juxt/edge#118]
I have tried a couple of different project and everytime I enter (go) at the repl I get the following error message:

Execution error (IllegalArgumentException) at integrant.core/try-build-action (core.cljc:292).
No method in multimethod 'init-key' for dispatch value: :trustblocks.api.core/string

**Comment by SevereOverfl0w** [comment]
How did you create the project? What changes did you make after that?

**Comment by tbrooke** [comment]
I went and cloned the "Shop" repo and started that way but I went back and followed the Edge instructions to create a directory and pull in Edge - everything works now. I figure the problem was setting the init-key with Integrant

**Comment by SevereOverfl0w** [comment]
I'm a bit confused, but if you're happy then I'll close the issue. Please report back with any other issues.
