### ISSUE TITLE
deduce-version-from-git Error with shell command

### ISSUE THREAD

**Issue by snichme** [juxt/edge#19]
Thanks for a great project setup to get started, I'm pretty new to the whole Clojure world and this is greatly appreciated!

I just pulled down the latest changes from github and after that `boot dev` will not start, it gives me an java.lang.NumberFormatException. 
The problem after a bit of testing was this new function `deduce-version-from-git` introduced here: https://github.com/juxt/edge/commit/7c54b2666ea39cd58edd190284e76a9581f396eb
When I run this command (both in the repl and in my terminal) I get: 
```
$ git describe --dirty --long --tags --match "[0-9].*"
fatal: No names found, cannot describe anything.
```
If I run without the --match flag I get: metail-115-gce4a740-dirty

Not sure what the desired output should be so I won't open a PR.

**Comment by piyush123** [comment]
Hi I am having the same issue.  Thank you snichme for confirming it wasn't just me.

**Comment by SevereOverfl0w** [comment]
```patch
diff --git a/build.boot b/build.boot
index a3cc62f..7079be7 100644
--- a/build.boot
+++ b/build.boot
@@ -29,7 +29,7 @@
       :otherwise version)))
 
 (def project "edge")
-(def version (deduce-version-from-git))
+(def version "0.1.0")
 
 (set-env!
  :source-paths #{"sass" "src"}
```

This patch is a _workaround_ which disables the git-based versioning for now. Copy it to a file (e.g. `removededuce.patch`) and run `git apply removededuce.patch` to run it.

**Comment by malcolmsparks** [comment]
Apologies - I hadn't pushed the signed tag from my own system. This should be fixed now.
