### ISSUE TITLE
Document how to package and run in production?

### ISSUE THREAD

**Issue by vvvvalvalval** [juxt/edge#31]
It would be good to have recommendations about how to deploy in a production environment.

**Comment by danielcompton** [comment]
I'm not sure if there's any documentation, but the boot file does show how to build an uberjar and deploy to elastic beanstalk. Docs would be good too though.

**Comment by vvvvalvalval** [comment]
@danielcompton this may be due to my lack of experience with Boot, but I don't see any Boot file in the [current version of master](https://github.com/juxt/edge/tree/58249a589a44ca40011c2a694496e157cb39d99f).

**Comment by danielcompton** [comment]
Haha whoops, I was going off my usage from a forked version from about a year ago. Sorry!

**Comment by SevereOverfl0w** [comment]
We noticed this internally, and we've been discussing it. We have a few things we want to document & provide existing configuration for. We're wanting to work towards an overarching documentation strategy which has references to the appropriate projects.

My quick recommendation is to use https://github.com/juxt/pack.alpha but also to consider just doing `clojure -m edge.main`.

**Comment by SevereOverfl0w** [comment]
https://github.com/juxt/edge/commit/bfb980ab5d35f624fd50ee5c76bf3d6f785bfef3 I've created an alpha uberjar script for example purposes. I'm classing it alpha because I'm not entirely confident about including AOT by default, it's not necessary with pack.

Hopefully this helps you with deploying your app to production.

**Comment by SevereOverfl0w** [comment]
https://github.com/juxt/edge/commit/d8d0603d93ebbc10bacc8e43aee04e34ae07d019 I've added some documentation for two options for release: UberJAR and CLI tools.

**Comment by vvvvalvalval** [comment]
@SevereOverfl0w thanks! In [bin/uberjar](https://github.com/juxt/edge/blob/d8d0603d93ebbc10bacc8e43aee04e34ae07d019/bin/uberjar#L18,) at the AOT compliation step, there seems to be a redundancy between `-A:aot` and specifying the AOT JVM properties inline (`-J-Dclojure.compiler.elide-meta` etc.)

**Comment by SevereOverfl0w** [comment]
Quite right, fixed!
