### ISSUE TITLE
krei does not seem to hotreload changes to cljs code

### ISSUE THREAD

**Issue by sooheon** [juxt/edge#33]
After running edge, changing the hiccup in `phonebook_app.cljs` cases a page refresh but the change is not reflected. Even after killing and restarting the `bin/repl` process, changes aren't reflected.

If I check the target directory, the relevant cljs and js files have the right timestamps, but hold outdated code. 

What could be the issue?

**Comment by SevereOverfl0w** [comment]
Edge has moved on to kick now. Phonebook looks quite different. Please reopen if this is still an issue.
