### ISSUE TITLE
Unable to run `(go)` - no nREPL in classpath

### ISSUE THREAD

**Issue by p-himik** [juxt/edge#44]
```bash
edge/main$ git rev-parse HEAD
248512d1db83eccdbe6a1db223cc626d5a3ea0f6
```
```bash
edge/main$ ../bin/rebel -A:dev:build:dev/rebel
[Edge] Starting development environment, please wait…
[Rebel readline] Type :repl/help for online help info
[Edge] Loading Clojure code, please wait...
[Edge] Now enter (go) to start the dev system
dev=> (go)
CompilerException java.io.FileNotFoundException: Could not locate nrepl/server__init.class or nrepl/server.clj on classpath., compiling:(figwheel_sidecar/components/nrepl_server.clj:6:1) 
dev=>
```

This commit added `org.clojure/tools.nrepl` to the exclusions in `figwheel-sidecar` dependency: https://github.com/juxt/edge/commit/e8796179db507cc416045ca5d10fd70610266dfe
If I remove the exclusion, `(go)` appears to be working.

**Comment by SevereOverfl0w** [comment]
The background here is that loading tools.nrepl into the classpath causes issues with tools which have moved on, like cider.

I think we need to substitute in nrepl/nrepl in place of tools.nrepl. Figwheel supports this.

**Comment by SevereOverfl0w** [comment]
Also, I don't think you need the `-A:dev/rebel` for your usage. I'm going to remove that alias, and update `bin/repl` as an alias to `../rebel`.
