### ISSUE TITLE
Create edge index page

### ISSUE THREAD

**Issue by SevereOverfl0w** [juxt/edge#55]
Provide a page which lists useful links, for example:

1. Link to auto-tests (if on)
2. Link to root of main web server
3. Link to devcards
4. Custom links to particular areas of site (maybe with custom js to log you in for example? uncertain, could be done via having a special url which did the work too).

Harvesting these links should be extensible in some way.
They should be hosted ???.
Figwheel extra mains would be _convenient_ but aren't universally available, and edge is supposed to be agnostic.
One option would be to start a _third_ web server to host this, but I think 2 is already too many.

**Comment by malcolmsparks** [comment]
The create-react-app my-app has a nice index page with a hint to the next step.
It would also be nice to add an Edge logo.

**Comment by SevereOverfl0w** [comment]
Alternative: Use https://github.com/Yomguithereal/react-blessed (via https://github.com/eccentric-j/cljs-cli-template) to create a console-based developer tooling set:

Benefits:
- No requirement on Cljs (for cljs-less projects, e.g. api-only)
Costs:
- Requires re-implementing some visual test feedback

There's opportunity to do more than cljs-test-display, in that we could show results for clojure tests too, maybe via kaocha. Lots of ideas here.

**Comment by SevereOverfl0w** [comment]
Links, of course can be shown via println. So I currently think this issue lacks detail of any strong reason to start a web server beyond it looking nice and being fun.

**Comment by SevereOverfl0w** [comment]
Links to auto-tests are now shown via `println` on `(go)` or `(resume)` when auto-testing is enabled.

**Comment by SevereOverfl0w** [comment]
Can't justify this, closing.
