### ISSUE TITLE
boot dev not working for yada branch

### ISSUE THREAD

**Issue by markmelling** [juxt/edge#6]
In the yada branch 

`boot dev`

fails as aero is not included in the dependencies in build.boot.

I added this dependency along with updating the versions of some of the other dependencies whilst I was there. I'm not sure if this is a consequence of updating yada to 1.1.11, but I also needed to change the server.clj stop code to make make reloaded.repl/reset work, specifically to:

`(stop [component]
    (when-let [server (:server component)]
      ((:close server)))
    component)`

previously it was 

`(stop [component]
    (when-let [server (:server component)]
      (.close server))
    component))`

Changes in forked version here: https://github.com/markmelling/edge/tree/yada

**Comment by SevereOverfl0w** [comment]
I really appreciate you pointing this out to us.

I wanted to let you know that we've merged the yada branch into master now, and that's the best place to try out yada.

**Comment by markmelling** [comment]
I'm glad I was able to help, even if it was a very small contribution.
