### ISSUE TITLE
Add Emacs instructions for cljs apps

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/edge#61]
CIDER 21.1 is asking for the following on `M-x cider-jack-in-clj&cljs`:

```
Select ClojureScript REPL type:
```
(perhaps this should be written into `.dir-locals.el`)

```
Select figwheel-main build (e.g. :dev):
```

Not sure what to put here. If I try 'app' I get the following error:

```
Execution error (ExceptionInfo) at cljs.cli/missing-file (cli.clj:192).
File app.cljs.edn does not exist
```

**Comment by SevereOverfl0w** [comment]
The current solution is to cancel the prompt when it pops up, then manually resolve the pending cljs repl.

Someone with access to emacs should test the custom approach though, then we can document that for emacs in the dev guide.

**Comment by malcolmsparks** [comment]
Happy to test the use of custom, I just found this non-intuitive.
