### ISSUE TITLE
`edge.yada.ig/hosts` for "bidi.vhosts.VHostsModel" does not handle `:*`

### ISSUE THREAD

**Issue by p-himik** [juxt/edge#67]
Bidi accepts `:*` as a vhost, it doesn't parse it in any way and just passes as is.
But https://github.com/juxt/edge/blob/master/lib/edge.ig.yada/src/edge/yada/ig.clj#L41 assumes that the host has been parsed into a map of `:scheme` and `:host`.
It leads to `Execution error (NullPointerException) at edge.yada.ig/eval44369$fn$fn (ig.clj:41).
null` when executing `(go)`.

**Comment by SevereOverfl0w** [comment]
Makes sense to fix this by just pointing at localhost for this case.

**Comment by p-himik** [comment]
Not sure I follow. Why? Wouldn't it prevent it from working if I use `:*` in production?

**Comment by SevereOverfl0w** [comment]
Hosts is used to inform the user where the web server is running during development.

**Comment by p-himik** [comment]
Gotcha, thanks.
