### ISSUE TITLE
`test-all` has a regex hardcoded to edge tests

### ISSUE THREAD

**Issue by SevereOverfl0w** [juxt/edge#80]
This could potentially use orchard to find test-namespaces using the var-query tools in that project.

**Comment by SevereOverfl0w** [comment]
this just shouldn't use a regex at all

**Comment by danielcompton** [comment]
Yeah, you could rely on orchard or perhaps just eftest's `find-tests` and pass it a "test" directory to work with.

**Comment by SevereOverfl0w** [comment]
I wrote the orchard stuff, so I felt comfortable rewriting the way the test finder works as it's quite simple.
