### ISSUE TITLE
Use .container instead of .container-fluid for Last Updated date

### ISSUE THREAD

**Issue by danielcompton** [juxt/edge#84]
On https://juxt.pro/edge/docs/lifecycle.html the Last Updated section is wrapped in a `.container-fluid` div. I think if that was `.container` then it would line up with the rest of the documentation?

<img width="1459" alt="Screenshot of Safari (20-06-19, 8-01-16 AM)" src="https://user-images.githubusercontent.com/811954/59796429-97bdf500-9331-11e9-955d-39b5eb98cc79.png">

**Comment by SevereOverfl0w** [comment]
I've been trying to decide where to put this. I did briefly put it into the footer. You're right that a .container would be a quick win for better alignment.

Changed, Thanks!
