### ISSUE TITLE
classpath error starting repl in freshly created app

### ISSUE THREAD

**Issue by PEZ** [juxt/edge#90]
I fail to start the app following the instructions here: https://juxt.pro/edge/docs/setup.html

This is what I did:

1. created a new repository
1. added Edge to my project
1. created a new app: `$ ./bin/app acme/app --cljs`
1. started a terminal repl: `$ ../bin/rebel --cljs -A:dev:dev/build:build` 

It gives me the following error:

```
Error building classpath. Manifest type not detected when finding deps for juxt.edge/app.logging in coordinate #:local{:root "../edge.app.logging"}
```

**Comment by SevereOverfl0w** [comment]
This would probably indicate you have an out of date version of clj, can you do `clj -Sdescribe `?

**Comment by PEZ** [comment]
Yes, that was the problem. (`clj -Sdescribe` didn't even work).
