### ISSUE TITLE
Using dev namespace instead of user?

### ISSUE THREAD

**Issue by danielcompton** [juxt/edge#97]
https://github.com/juxt/edge/commit/f97caba81d68875474925b8770bd6945807739ce moved the main entry point for REPL development from `user.clj` to `dev.clj`. Does the release Clojure 1.10.1 with a [fix](https://clojure.org/news/2019/06/06/clojure1-10-1#_java_performance_regression) for the startup performance regression using `user.clj` change your perspective on having a separate `dev.clj`? Were there other reasons for making the switch too?

One reason I can think of is that it makes the initial startup time faster, as the automatic loading of user.clj doesn't require all of the app + dependency namespaces.

**Comment by SevereOverfl0w** [comment]
The main purpose is in a comment in that commit: https://github.com/juxt/edge/blob/f97caba81d68875474925b8770bd6945807739ce/app/dev/user.clj#L5 performance has nothing to do with it, that regression is newer than the change.

**Comment by danielcompton** [comment]
Ah yeah, that makes sense, I've definitely run into that before.
